### ISSUE TITLE
Hardcoded values

### ISSUE THREAD

**Issue by m-shinder** [JannikHv/gamebox#1]
if you try run gamebox without installation, images will not be displayed. Because binary look for images in /usr/share/gamebox/images and without installation it does not exist. I suggest 
* create CONFIG.h which would contain string defines (ex. IMAGE_PATH)
* add 'debug' make option which will compile project with gcc -DDEBUG
* in code use #ifdef DEBUG to compile debug-specific stuff
and example CONFIG.h:
`#ifdef DEBUG`
 `# define IMAGE_PATH "./images"`
 `#endif`
 `#ifndef DEBUG`
 `# define IMAGE_PATH "/usr/share/gamebox/images`
 `#endif`

your repo have no contribution info or rules, so i open the issue to ask you about this idea

**Comment by JannikHv** [comment]
@m-shinder I assume this is obsolete by your recent pull request?
